## Numpy basics 

In [2]:
import numpy as np
array_1d=np.array([1,2,3,4])
print(f"1D Array {array_1d}")

array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(f"2D Array :{array_2d}")

1D Array [1 2 3 4]
2D Array :[[1 2 3 4]
 [5 6 7 8]]


#### List vs Numpy Array

In [ ]:
python_list=[1,2,3,4]
print(f"Python list Multiplication {python_list * 2}")

np_array = np.array([1, 2, 3, 4]) # Elemeent vise multiplication 
print(f"Numpy Array Multiplication {np_array * 2}")

Python list Multiplication [1, 2, 3, 4, 1, 2, 3, 4]
Numpy Array Multiplication [2 4 6 8]


#### Creating Array from Scratch 

In [ ]:
zero_array = np.zeros((2,3))
print(f"Zeros Array \n {zero_array}")
ones_array = np.ones((3, 4))
print(f"Ones Array \n {ones_array}")
full = np.full((2, 3), 10)
print(f"Full Array , \n {full}")
random = np.random.random((2, 3))
print(f"Random values array  {random}")
sequence = np.arange(0, 50, 5) # start (0) , stop (50) , step (5)
print(f"Sequence values printing : {sequence}")

Zeros Array 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array , 
 [[10 10 10]
 [10 10 10]]
Random values array  [[0.13401305 0.4226913  0.08807634]
 [0.48446865 0.29244653 0.79986957]]
Sequence values printing : [ 0  5 10 15 20 25 30 35 40 45]


#### Vector , Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
print(f"Vector : {vector}")
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"Matrix {matrix}")
tensor = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]]) # tensors are multi dimensional
print(f"tensor : {tensor}")

Vector : [1 2 3 4 5]
Matrix [[1 2 3 4]
 [5 6 7 8]]
tensor : [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


#### Array Properties

In [20]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Shape of Array {array.shape}") # number of rows and columns
print(f"Dimension of Array {array.ndim}D") # dimension of array 
print(f"Size of Array {array.size}") # total number of elements in array 
print(f"Datatype  of Array {array.dtype}") # datatype of array 

Shape of Array (2, 3)
Dimension of Array 2D
Size of Array 6
Datatype  of Array int32


#### Array Reshaping

In [31]:
array = np.arange(12)
print("Original Array :", array)
reshape = array.reshape((3,4)) # returns copy of original array
print(f"reshaped array : {reshape}")
flatten = reshape.flatten()
print(f"Flattened Array {flatten}")
revel = reshape.ravel() # return the original array
print(f"revel : {revel}")
transpose = reshape.T
print(f"Transposed array : {transpose}")

Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
revel : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
